package org.jooq.util.maven.jpa.writer;

import org.jooq.util.JavaWriter;
import org.jooq.util.maven.jpa.model.JPAEntity;

import java.io.File;

/**
 * TODO write documentation<br>
 *<br>
 * Created at 09/08/13 11:52.<br>
 *
 * @author Kevin
 * @since 2.10
 *
 */
public class EntitiesFileWriter {

	JavaWriter out;

	public EntitiesFileWriter(File directory, String packageName) {
		out = new JavaWriter(new File(directory, "Entities.java"));
		out.javadoc("This class is generated by jOOQ");
		out.println("package %s;", packageName);
		out.println();
		// generate the table representation with the class name pointing to the jooq table name
		//	printClassJavadoc(out, "JPA entities representation.");
		out.println("public class Entities {");
	}

	public void addEntity(Class<?> jpaEntityClass) {
		JPAEntity entity = new JPAEntity(jpaEntityClass);
		String entityName = entity.getJpaEntityName();
		String tableName = entity.getTableName();
		out.println("public static final %s %s = %s.%s;", entityName, entity.getClassName().toUpperCase(),
				entityName, tableName);
	}

	public void close() {
		out.println("}");
		out.close();
	}
}
